CONFIG = {
    "SHODAN_API_KEY": "",
    "VIRUSTOTAL_API_KEY": "",
    "CENSYS_API_ID": "",
    "CENSYS_API_SECRET": "",
    "HUNTER_API_KEY": "",
    "GITHUB_TOKEN": "",
    "HIBP_API_KEY": "",
    "BUILTWITH_API_KEY": "",
    "SECURITYTRAILS_API_KEY": "",
    "REQUEST_TIMEOUT": 15,
    "REQUEST_DELAY": 1,
    "MAX_SUBDOMAINS": 500,
    "MAX_IPS_TO_SCAN": 50,
    "THREADS": 10,
    "OUTPUT_DIR": "./output",
    "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
}
